---
- name: Create ~/.kube/
  file:
    path: "/home/{{ user | default(ansible_user) }}/.kube/"
    state: directory
    owner: "{{ user | default(ansible_user) }}"
    group: "{{ user | default(ansible_user) }}"
    mode: 0700
  become: yes

- name: Create kubeconfig
  copy:
    dest: "/home/{{ user | default(ansible_user) }}/.kube/config"
    owner: "{{ user | default(ansible_user) }}"
    group: "{{ user | default(ansible_user) }}"
    mode: 0600
    content: "{{ hostvars[groups['control'] | intersect(groups[key_name]) | first]['kubeconfig_base64'] | b64decode }}"
  become: yes
